# Generated by Django 2.2.3 on 2019-08-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=50, verbose_name='Book Name')),
                ('bookPages', models.CharField(max_length=50, verbose_name='Book Pages')),
                ('bookPrice', models.CharField(max_length=50, verbose_name='Book Price')),
            ],
        ),
    ]
