# Generated by Django 2.2.3 on 2019-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Book Name'),
        ),
    ]
